services:
  yazio-overview:
    build: .
    container_name: yazio-overview
    ports:
      - "8080:8080"
    environment:
      YAZIO_DEMO_MODE: "false"
      YAZIO_USER_MANAGEMENT: "false"
      YAZIO_ADMIN_PASSWORD: "admin"
      DEVELOPER: "0"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
